### ISSUE TITLE
Expose "Timer" in instead of "BlockTimer" and "FunctionTimer"

### ISSUE THREAD

**Issue by prashanthellina** [deep-compute/deeputil#22]
In documentation also, just showcase "Timer" instead of the other two.

**Comment by supriyopaul** [comment]
@prashanthellina should we also have Block Counter & Function Counter? Just a thought?

**Comment by prashanthellina** [comment]
@supriyopaul Hmmm ... Not sure I understand the use-case. Can you bring this up for discussion when we meet please?

**Comment by supriyopaul** [comment]
Now it is working in an alternative way, Not sure if this is very important now.

**Comment by supriyopaul** [comment]
not working on this repo for now.

**Comment by jaswanth098** [comment]
Not actively working

**Comment by sundarrajan78** [comment]
This will be taken up post completing other priority Deepql issues

**Comment by sundarrajan78** [comment]
Low priority
