### ISSUE TITLE
Add grouper functionality

### ISSUE THREAD

**Issue by praneeth36** [deep-compute/deeputil#29]
Iterate on an iterator by chunks
Ref: https://stackoverflow.com/questions/8991506/iterate-an-iterator-by-chunks-of-n-in-python/8991553#8991553

**Comment by jaswanth098** [comment]
@praneeth36 The code is merged and deployed to Pypi, now you can use below command to download latest package
pip install deeputil==0.2.9

**Comment by praneeth36** [comment]
Thank you @jaswanth098.

Closing this ==>
