### ISSUE TITLE
Issue with AttrDict

### ISSUE THREAD

**Issue by jaswanth098** [deep-compute/deeputil#35]
```python3
>>> from deeputil import AttrDict
>>> a = AttrDict({"b": {}})
>>> a.b.c = 1
>>> a
AttrDict({'b': {}})
>>> a.c = 1
>>> a
AttrDict({'b': {}, 'c': 1})
>>> 
```

On the top level of dictionary values are getting manipulated but the internal dictionary is not getting updated with any values provided

**Comment by jaswanth098** [comment]
Will get back to this later

**Comment by jaswanth098** [comment]
not prio and also needs some thinking

**Comment by sundarrajan78** [comment]
@prashanthellina Can we close this issue?

**Comment by prashanthellina** [comment]
I'll keep this open for now. snoozing.

**Comment by sundarrajan78** [comment]
Not a priority

**Comment by sundarrajan78** [comment]
Not a priority
